import os
import psycopg2
import pandas as pd
from typing import Tuple, Optional

def execute_query(query: str) -> Tuple[Optional[pd.DataFrame], Optional[str]]:
    """
    Executes SQL query in database and returns the result DataFrame.

    Args:
        query: Query generated by the LLM

    Returns:
        A tuple containing:
        - Pandas DataFrame with the query results when success, otherwise None
        - An error message string when failure, otherwise None
    """
    try:
        with psycopg2.connect(
        host=os.getenv("DB_HOST"),
        dbname=os.getenv("DB_NAME"),
        user=os.getenv("DB_USER"),
        password=os.getenv("DB_PASSWORD"),
        port=os.getenv("DB_PORT")
        ) as conn:
            result_df = pd.read_sql_query(query, conn)
            return result_df, None

    except Exception as e:
        print(f"[ERROR] Failed to execute query: {e}")
        return None, str(e)