import duckdb
import pandas as pd
from typing import Tuple, Optional

def execute_query(query: str) -> Tuple[Optional[pd.DataFrame], Optional[str]]:
    """
    Executes SQL query in database and returns the result DataFrame.

    Args:
        query: Query generated by the LLM

    Returns:
        A tuple containing:
        - Pandas DataFrame with the query results when success, otherwise None
        - An error message string when failure, otherwise None
    """
    try:
        with duckdb.connect(database='walle-prod.duckdb', read_only=True) as conn:
            result_df = conn.sql(query).df()
            return result_df, None

    except Exception as e:
        print(f"[ERROR] Failed to execute query: {e}")
        return None, str(e)